-- exploratory_queries.sql
-- Sprint 1 / Day 07 deliverable — 10 sanity/exploration queries against nifty100.db

-- 1. Total companies loaded (must equal 92)
SELECT COUNT(*) AS total_companies FROM companies;

-- 2. Row counts per core table
SELECT 'profitandloss' AS tbl, COUNT(*) AS rows FROM profitandloss
UNION ALL SELECT 'balancesheet', COUNT(*) FROM balancesheet
UNION ALL SELECT 'cashflow', COUNT(*) FROM cashflow
UNION ALL SELECT 'stock_prices', COUNT(*) FROM stock_prices
UNION ALL SELECT 'documents', COUNT(*) FROM documents;

-- 3. Companies with fewer than 5 years of P&L data (candidates for manual review, Day 06)
SELECT company_id, COUNT(DISTINCT year) AS years_of_data
FROM profitandloss
GROUP BY company_id
HAVING years_of_data < 5
ORDER BY years_of_data ASC;

-- 4. Sector distribution across the 92 companies
SELECT broad_sector, COUNT(*) AS company_count
FROM sectors
GROUP BY broad_sector
ORDER BY company_count DESC;

-- 5. Companies with the highest source roe_percentage (display-only, pre-computed)
SELECT company_id, company_name, roe_percentage, roce_percentage
FROM companies
ORDER BY roe_percentage DESC
LIMIT 10;

-- 6. Latest available year of P&L data per company (first 15 alphabetically)
SELECT company_id, MAX(year) AS latest_period
FROM profitandloss
GROUP BY company_id
ORDER BY company_id
LIMIT 15;

-- 7. Peer groups and their member counts
SELECT peer_group_name, COUNT(*) AS members,
       SUM(is_benchmark) AS benchmark_flags
FROM peer_groups
GROUP BY peer_group_name
ORDER BY members DESC;

-- 8. Balance sheet imbalance spot-check (assets vs liabilities, ordered by worst)
SELECT company_id, year, total_assets, total_liabilities,
       ROUND(ABS(total_assets - total_liabilities) * 100.0 / NULLIF(total_liabilities, 0), 2) AS diff_pct
FROM balancesheet
WHERE total_liabilities IS NOT NULL AND total_liabilities != 0
ORDER BY diff_pct DESC
LIMIT 10;

-- 9. Average monthly close price by sector (joins stock_prices -> sectors)
SELECT s.broad_sector, ROUND(AVG(sp.close_price), 2) AS avg_close_price
FROM stock_prices sp
JOIN sectors s ON sp.company_id = s.company_id
GROUP BY s.broad_sector
ORDER BY avg_close_price DESC;

-- 10. Data quality summary: CRITICAL vs WARNING counts by rule (cross-reference with
--     output/validation_failures.csv, generated by the loader/validator, not stored in DB)
-- (Run separately in Python/pandas: pd.read_csv('output/validation_failures.csv')
--  .groupby(['rule_id','severity']).size())
